# Print the report generated by the Turbo optimization
# PRINT_FULL_REPORT			:	BOOLEAN					:= TRUE;

# -------------- PRINT_FULL_REPORT ------------
set DEFAULT_PRINT_FULL_REPORT "FALSE"

set enablement {False}
set editable {expr [expr {$MD_VS_TD} == "{TD}"]}

set dependency {}

set tooltip "Print the report of the Turbo Decoder pre-processor"
set display_name "Print Full Report"

set_param_bool "PRINT_FULL_REPORT" $DEFAULT_PRINT_FULL_REPORT $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------
