# CEC coarse counter generated by the internal CoarseExtensionCore, CTD coarse counter came from external CoarseTreeDistribution
# CEC_VS_CTD_COUNTER	:	STRING						:= "CEC";

# --------------CEC_VS_CTD_COUNTER---------------
set LIST_CEC_VS_CTD_COUNTER {CEC CTD}
set DEFAULT_CEC_VS_CTD_COUNTER "CEC"

set enablement {True}
set editable {}

set dependency {}


set tooltip "Choice between the interal Coarse Counter inside the Coarse Extension Core (CEC) sub-module and the external Coarse Tree Distributor (CTD)"
set display_name "Coarse Extension Core vs Coarse Tree Distributor"

set_param_string_list "CEC_VS_CTD_COUNTER" $LIST_CEC_VS_CTD_COUNTER $DEFAULT_CEC_VS_CTD_COUNTER $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------
