# Function ID of the Belt Bus 0 = OVERLOW Coarse, 1 = MEASURE, If 0 no FID is consider
# BIT_FID				:	NATURAL	:=	1;

# ------------------ BIT_FID -------------------
set MIN_BIT_FID 0
set MAX_BIT_FID 4
set DEFAULT_BIT_FID 1

set enablement {True}
set editable {}

set dependency {}

set tooltip "Bit reserved to the FID of the Belt Bus used to identify properly the timestamps"
set display_name "Bit FID"

create_param_long_range "BIT_FID" $MIN_BIT_FID $MAX_BIT_FID $DEFAULT_BIT_FID $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------



# Bit of Coarse Counter, If 0 not Coarse counter is consider only Fine
# BIT_COARSE		:	NATURAL		RANGE	0	TO	32	:=	8;

# ---------------- BIT_COARSE -----------------
set MIN_BIT_COARSE 0
set MAX_BIT_COARSE 32
set DEFAULT_BIT_COARSE 8

set enablement {True}
set editable {}

set dependency {}

set tooltip "Bit Coarse Counter dimension"
set display_name "Bit Coarse"

create_param_long_range "BIT_COARSE" $MIN_BIT_COARSE $MAX_BIT_COARSE $DEFAULT_BIT_COARSE $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------




# Number od Bit of Uncalibrated_TDL (0 : 2^BIT_UNCALIBRATED-1 is the memory length)
# BIT_UNCALIBRATED	:	POSITIVE	RANGE	2	TO	16	:=	8;

# -------------- BIT_UNCALIBRATED --------------
set MIN_BIT_UNCALIBRATED 2
set MAX_BIT_UNCALIBRATED 16
set DEFAULT_BIT_UNCALIBRATED 8

set enablement {True}
set editable {}

set dependency {}

set tooltip "Bit Dimension of Uncalibrated_TDL"
set display_name "Bit Uncalibrated"

create_param_long_range "BIT_UNCALIBRATED" $MIN_BIT_UNCALIBRATED $MAX_BIT_UNCALIBRATED $DEFAULT_BIT_UNCALIBRATED $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------




# CEC coarse counter generated by the internal CoarseExtensionCore, CTD coarse counter came from external CoarseTreeDistribution
# CEC_VS_CTD_COUNTER	:	STRING						:= "CEC";

# --------------CEC_VS_CTD_COUNTER---------------
set LIST_CEC_VS_CTD_COUNTER {CEC CTD}
set DEFAULT_CEC_VS_CTD_COUNTER "CEC"

set enablement {True}
set editable {}

set dependency {}


set tooltip "Choice between the interal Coarse Counter inside the Coarse Extension Core (CEC) sub-module and the external Coarse Tree Distributor (CTD)"
set display_name "Coarse Extension Core vs Coarse Tree Distributor"

create_param_string_list "CEC_VS_CTD_COUNTER" $LIST_CEC_VS_CTD_COUNTER $DEFAULT_CEC_VS_CTD_COUNTER $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------

# Initialization Value of the Internal Coarse Counter in CoarseExtensionCore
# CEC_COARSE_CNT_INIT	:	NATURAL						:= 0;

# ------------- CEC_COARSE_CNT_INIT -----------
set MIN_CEC_COARSE_CNT_INIT 0
set MAX_CEC_COARSE_CNT_INIT [expr 2**[get_property value [ipx::get_user_parameters BIT_COARSE -of_objects [ipx::current_core]]] -1]
set DEFAULT_CEC_COARSE_CNT_INIT 0

set enablement {True}
set editable {[expr {$CEC_VS_CTD_COUNTER} == "{CEC}"]}

set dependency {}

set tooltip "Initialization value of the CEC Coarse Counter"
set display_name "CEC Coarse Counter Initialization"

create_param_long_range "CEC_COARSE_CNT_INIT" $MIN_CEC_COARSE_CNT_INIT $MAX_CEC_COARSE_CNT_INIT $DEFAULT_CEC_COARSE_CNT_INIT $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------






#Type of FIFO; "auto", "block", or "distributed";
#FIFO_MEMORY_TYPE	:	STRING							:=	"distributed";

# -------------- FIFO_MEMORY_TYPE ---------------
set LIST_FIFO_MEMORY_TYPE {auto block distributed}
set DEFAULT_FIFO_MEMORY_TYPE "distributed"

set enablement {True}
set editable {}

set dependency {}

set tooltip "Synchronizer FIFO type"
set display_name "Synchronizer FIFO Type"

create_param_string_list "FIFO_MEMORY_TYPE" $LIST_FIFO_MEMORY_TYPE $DEFAULT_FIFO_MEMORY_TYPE $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------


#FIFO Depth, Power of 2
#FIFO_WRITE_DEPTH	:	INTEGER	RANGE	16	TO	4194304	:=	16;

# -------------- FIFO_WRITE_DEPTH ---------------
set LIST_FIFO_WRITE_DEPTH "[expr 2**4]"
for {set i 5} {$i < 23} {incr i} {
	lappend LIST_FIFO_WRITE_DEPTH "[expr 2**$i]"
}

set DEFAULT_FIFO_WRITE_DEPTH [lindex $LIST_FIFO_WRITE_DEPTH 0]

set enablement {True}

set editable {}
set dependency {}

set tooltip "Synchronizer FIFO Depth"
set display_name "Synchronizer FIFO Depth"

create_param_long_list "FIFO_WRITE_DEPTH" $LIST_FIFO_WRITE_DEPTH $DEFAULT_FIFO_WRITE_DEPTH $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------



# Select the max number of inputs for the AND gates in the second stage
# MAX_INPUT_ENGINE_AND_PIPELINE_STAGE1	:	POSITIVE := 3;

# ---------------- MAX_INPUT_ENGINE_AND_PIPELINE_STAGE1 -----------------
set MIN_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE1 2
set MAX_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE1 8
set DEFAULT_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE1 4

set enablement {True}
set editable {}

set dependency {}

set tooltip "Select the maximum number of inputs for the AND gates in the second stage"
set display_name "Maximum Number of inputs of the engines of the second stage"

create_param_long_range "MAX_INPUT_ENGINE_AND_PIPELINE_STAGE1" $MIN_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE1 $MAX_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE1 $DEFAULT_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE1 $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------



# Select the max number of inputs for the AND gates in the third stage
# MAX_INPUT_ENGINE_AND_PIPELINE_STAGE2	:	POSITIVE := 3;

# ---------------- MAX_INPUT_ENGINE_AND_PIPELINE_STAGE2 -----------------
set MIN_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE2 2
set MAX_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE2 8
set DEFAULT_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE2 4

set enablement {True}
set editable {}

set dependency {}

set tooltip "Select the maximum number of inputs for the AND gates in the third stage"
set display_name "Maximum Number of inputs of the engines of the third stage"

create_param_long_range "MAX_INPUT_ENGINE_AND_PIPELINE_STAGE2" $MIN_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE2 $MAX_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE2 $DEFAULT_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE2 $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------


# Select the max number of inputs for the AND gates in the fourth stage
# MAX_INPUT_ENGINE_AND_PIPELINE_STAGE3	:	POSITIVE := 3;

# ---------------- MAX_INPUT_ENGINE_AND_PIPELINE_STAGE3 -----------------
set MIN_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE3 2
set MAX_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE3 8
set DEFAULT_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE3 4

set enablement {True}
set editable {}

set dependency {}

set tooltip "Select the maximum number of inputs for the AND gates in the fourth stage"
set display_name "Maximum Number of inputs of the engines of the fourth stage"

create_param_long_range "MAX_INPUT_ENGINE_AND_PIPELINE_STAGE3" $MIN_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE3 $MAX_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE3 $DEFAULT_MAX_INPUT_ENGINE_AND_PIPELINE_STAGE3 $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------



# Blocks of bits of the inputs that we want to compare in the first stage (Equality comparison)
# MAX_NUM_BIT_EQ_PIPELINE_STAGE0		: 	POSITIVE 	RANGE 1 TO 16   := 3;

# ---------------- MAX_NUM_BIT_EQ_PIPELINE_STAGE0 -----------------
set MIN_MAX_NUM_BIT_EQ_PIPELINE_STAGE0 1
set MAX_MAX_NUM_BIT_EQ_PIPELINE_STAGE0 [expr [get_property value [ipx::get_user_parameters BIT_COARSE -of_objects [ipx::current_core]]]]
set DEFAULT_MAX_NUM_BIT_EQ_PIPELINE_STAGE0 4

set enablement {True}
set editable {}

set dependency {}

set tooltip "Blocks of bits of the inputs that we want to compare in the first stage"
set display_name "Blocks of bits to be compared in the first stage"

create_param_long_range "MAX_NUM_BIT_EQ_PIPELINE_STAGE0" $MIN_MAX_NUM_BIT_EQ_PIPELINE_STAGE0 $MAX_MAX_NUM_BIT_EQ_PIPELINE_STAGE0 $DEFAULT_MAX_NUM_BIT_EQ_PIPELINE_STAGE0 $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------



#Specifies if the wr_clk (s00_uncalibTDC_aclk) and rd_clk (m00_uncalibSYS_aclk) are related, if 1 clk_TDC and clk_SYS are locked
#RELATED_CLOCKS		:	INTEGER	RANGE	0	TO	1		:=	0;

# --------------- RELATED_CLOCKS ---------------
set DEFAULT_RELATED_CLOCKS "FALSE"

set enablement {True}
set editable {}

set dependency {}

set tooltip "Phase relation between TDC and SYS clocks"
set display_name "TDC and SYS Clocks Relation"

create_param_bool "RELATED_CLOCKS" $DEFAULT_RELATED_CLOCKS $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------


#Cross Domain Clock Synch Stages: specifies the number of synchronization stages on the CDC path. It must be < 5 if *FIFO_WRITE_DEPTH = 16*
#CDC_SYNC_STAGES		:	INTEGER	RANGE	2	TO	8		:=	4;

# --------------- CDC_SYNC_STAGES --------------
set MIN_CDC_SYNC_STAGES 2
set MAX_CDC_SYNC_STAGES 8
set DEFAULT_CDC_SYNC_STAGES 4

set enablement {True}
set editable {expr [expr {$RELATED_CLOCKS} != "{true}"]}

set dependency {}

set tooltip "Synchronization CDC stages in the FIFO"
set display_name "Synchronizer FIFO CDC Stages"

create_param_long_range "CDC_SYNC_STAGES" $MIN_CDC_SYNC_STAGES $MAX_CDC_SYNC_STAGES $DEFAULT_CDC_SYNC_STAGES $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------


# Generic used for deciding whether to count the overflows in the CEC (if *INTERNAL_OVERFLOW_CNT* is TRUE) or leave the Overfow Counter the task of counting (if *INTERNAL_OVERFLOW_CNT* is FALSE)
# INTERNAL_OVERFLOW_CNT	:	BOOLEAN		:=	FALSE

# ------------- INTERNAL_OVERFLOW_CNT ----------
set DEFAULT_INTERNAL_OVERFLOW_CNT "FALSE"

set enablement {True}
set editable {}

set dependency {}

set tooltip "Enabling the CEC (if TRUE) or the OC (if FALSE) to count the overflows"
set display_name "Overflow Counter in CEC or in OC"

create_param_bool "INTERNAL_OVERFLOW_CNT" $DEFAULT_INTERNAL_OVERFLOW_CNT $enablement $editable $dependency $tooltip $display_name
# ----------------------------------------------
